const { db } = require("../config/firebaseAdmin"); // 🔹 Assure-toi que le chemin vers firebaseAdmin.js est correct

const revendeurs = [
  {
    codeAdherent: "ATLA4440",
    codeVendeur: "ADV FRANCE",
    company: "ATLANTIC TRUCK SERVICES",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "44470",
    telephone: "02 40 25 01 02",
    contact: "LUC LEPICIER",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "AUBI7900",
    codeVendeur: "ADV FRANCE",
    company: "AUBINEAU CONSTRUCTEUR",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "79700",
    telephone: "05 49 81 42 11",
    contact: "MR DE MALEZIEUX",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "BAIN2701",
    codeVendeur: "OGR",
    company: "CARROSSERIE INDUST BAIN",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "27110",
    telephone: "02 32 34 03 50",
    contact: "GEORGES BAIN",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "BARR6201",
    codeVendeur: "ADV FRANCE",
    company: "CARROSSERIE BARRE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "62220",
    telephone: "03 21 74 74 00",
    contact: "YOAN DESTREBECQ",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "BAYI7200",
    codeVendeur: "OGR",
    company: "SAS BAYI TRUCKS LE MANS",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "72028",
    telephone: "02 43 50 22 28",
    contact: "MR JOUIN",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "BIZI2901",
    codeVendeur: "OGR",
    company: "THE TRUCK COMPANY FRANCE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "29250",
    telephone: "02 98 29 21 00",
    contact: "ARNAUD GUIVARC",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "BLIN5100",
    codeVendeur: "OGR",
    company: "BLIN CARROSSERIE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "51420",
    telephone: "0326843232",
    contact: "",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "BOYR9902",
    codeVendeur: "ADV EXPORT",
    company: "BOYRITEC",
    paysRegion: "DE",
    groupeCompta: "CEE",
    codePostal: "56410",
    telephone: "0049 2602 9225",
    contact: "ANDREAS KASPAR",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "CARF8800",
    codeVendeur: "OGR",
    company: "CARFAR",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "88300",
    telephone: "03 29 94 18 93",
    contact: "NICOLAS RENAUT",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "CAVI7782",
    codeVendeur: "ADV FRANCE",
    company: "CAVIME",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "77820",
    telephone: "01 60 66 60 35",
    contact: "MR GARRIGUE FRANCIS ET HUP",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "CHER5006",
    codeVendeur: "OGR",
    company: "JEAN CHEREAU SAS",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "50220",
    telephone: "02 33 58 06 00",
    contact: "",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "CORS2802",
    codeVendeur: "OGR",
    company: "CARROSSERIE CORSIN",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "28130",
    telephone: "02 37 27 56 56",
    contact: "",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "DHUM2305",
    codeVendeur: "OGR",
    company: "DHUME CARROSSERIE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "23170",
    telephone: "05 55 82 11 06",
    contact: "FREDERIC DHUME",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "DUFI0801",
    codeVendeur: "OGR",
    company: "DUFILS CARROSSERIE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "08400",
    telephone: "03 24 71 86 08",
    contact: "BRUNO ROMAIN",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "GROS7605",
    codeVendeur: "OGR",
    company: "GROSSE EQUIPEMENT",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "76270",
    telephone: "02 35 93 09 30",
    contact: "FRANÇOIS GROSSE",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "ITAL5100",
    codeVendeur: "OGR",
    company: "ITAL EXPRESS",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "51009",
    telephone: "03 26 21 11 00",
    contact: "CYRIL DENIS",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LABB2200",
    codeVendeur: "OGR",
    company: "CARROSSERIE LABBE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "22405",
    telephone: "02 96 50 12 60",
    contact: "E CALVAR",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LALO9101",
    codeVendeur: "ADV FRANCE",
    company: "SAS LALOYEAU SERVICES",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "91150",
    telephone: "01 60 86 45 94",
    contact: "MR DUBUISSON",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LAMB0109",
    codeVendeur: "CTE PRINCIPAL",
    company: "LAMBERT SAS",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "01380",
    telephone: "03 85 30 85 30",
    contact: "EMMANUEL DELGADO",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LANG9500",
    codeVendeur: "ADV FRANCE",
    company: "DFCI LANGLAIS",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "95640",
    telephone: "01 34 67 50 98",
    contact: "",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LEBR5004",
    codeVendeur: "OGR",
    company: "CARROSSERIE LEBRUN",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "50160",
    telephone: "02 33 72 00 00",
    contact: "TURGIS PHILIPPE",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LECI3800",
    codeVendeur: "ADV EXPORT",
    company: "LECTRAILER FRANCE SARL",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "38290",
    telephone: "04 74 94 21 09",
    contact: "Cedric GRAND",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LECI9900",
    codeVendeur: "ADV EXPORT",
    company: "LECTRAILER SA",
    paysRegion: "ES",
    groupeCompta: "CEE",
    codePostal: "50620",
    telephone: "00 34 976462121",
    contact: "JAVIER AMADOR",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LEMA5914",
    codeVendeur: "OGR",
    company: "CARROSSERIE INDUST LEMAIRE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "59119",
    telephone: "03 27 88 87 61",
    contact: "Jérôme BAJWOULK",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LERO5605",
    codeVendeur: "ADV FRANCE",
    company: "LE ROUIC SARL",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "56250",
    telephone: "02 97 53 33 30",
    contact: "MICHEL QUINTIN HERVÉ LEROUIC",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LIBN7903",
    codeVendeur: "OGR",
    company: "LIBNER",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "79400",
    telephone: "05 49 05 78 78",
    contact: "achats@libner.fr",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "LOCA7200",
    codeVendeur: "OGR",
    company: "CRETOT LOCATION",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "72027",
    telephone: "02 43 50 26 20",
    contact: "BRIGITTE DEHAYE",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "MOLE8201",
    codeVendeur: "OGR",
    company: "MOLETTA OBRADO CARROSSERIE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "82000",
    telephone: "05 63 63 25 76",
    contact: "VÉRONIQUE RIOLS",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "REGN5020",
    codeVendeur: "OGR",
    company: "J RENAULT SAS",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "50208",
    telephone: "02 33 19 05 05",
    contact: "GAELLE CHAUSSAROT",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "SORI9900",
    codeVendeur: "ADV EXPORT",
    company: "SOR IBERICA",
    paysRegion: "ES",
    groupeCompta: "CEE",
    codePostal: "46600",
    telephone: "00 34 962457700",
    contact: "MARTA CARRASCOSA",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "TEKN7100",
    codeVendeur: "ADV FRANCE",
    company: "TEKNOKIT FRANCE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "71520",
    telephone: "03 85 50 95 60",
    contact: "CEDRIC BATHO",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "TOUT7204",
    codeVendeur: "ADV FRANCE",
    company: "TOUTAIN CARROSSERIE SAS",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "72202",
    telephone: "02 43 94 09 96",
    contact: "TEDDY MICHEL",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
  {
    codeAdherent: "VIVI6210",
    codeVendeur: "OGR",
    company: "VIVIER CARROSSERIE",
    paysRegion: "FR",
    groupeCompta: "FRANCE",
    codePostal: "62223",
    telephone: "03 21 24 04 00",
    contact: "Judicaelle",
    role: "Revendeur",
    createdAt: new Date().toISOString(),
  },
];

async function importRevendeurs() {
  try {
    for (const revendeur of revendeurs) {
      const userRef = db.collection("users_webapp").doc(revendeur.codeAdherent);
      await userRef.set(revendeur);
      console.log(`✅ Revendeur ajouté : ${revendeur.company}`);
    }
    console.log("🎉 Tous les revendeurs ont été ajoutés avec succès !");
  } catch (error) {
    console.error("❌ Erreur lors de l'importation des revendeurs :", error);
  }
}

importRevendeurs();
